### ISSUE TITLE
chistributed hangs when starting up non-compliant nodes

### ISSUE THREAD

**Issue by frank-lsf** [uchicago-cs/chistributed#2]
When the chistributed broker starts up a node, if an error occurs in the node's starting up process, or it does not respond to the hello message sent by the broker, the CLI hangs. It is unable to respond to further commands, and also cannot respond to Ctrl+C signals. The only way to get out of it is to manually kill the process with `kill -9`.

Is it possible to make the CLI more responsive when the node's start up process fails?

**Comment by borjasotomayor** [comment]
Partially fixed in https://github.com/uchicago-cs/chistributed/commit/592105dc53e5984a160095f67a57b074a27edb80

If a node process crashes at startup, then the interpreter will simply exit gracefully, since it will be hard to continue from there. It also now distinguishes between a "failed" node (one that is running but simply hasn't replied to the "hello" messages) and one that has actually crashed.
